const PLATFORM_KEY = 'BLBQ_V15_PLATFORM';
const METRIC_KEY = 'BLBQ_V15_METRICS';
const ACCOUNT_KEY = 'BLBQ_V20_ACCOUNTS';
const $p = (id) => document.getElementById(id);
const accounts = [
  { id: 'brand', name: '饱里宝气品牌主号', type: '品牌主号', store: '全门店', people: '长沙本地用户', focus: '品牌理念、门店合集、品牌信任', fans: 87 },
  { id: 'lin-ke-da', name: '饱里宝气轻食（林科大店）', type: '门店号', store: '林科大店', people: '林科大学生、宿舍党', focus: '下课吃饭、学生性价比、真实饭盒', fans: 403 },
  { id: 'health', name: '饱里宝气轻食健康餐', type: '健康饮食号', store: '全门店', people: '减脂、控糖、增肌人群', focus: '营养搭配、轻食知识、中式健康餐', fans: 807 },
  { id: 'mei-xi-hu', name: '饱里宝气轻食（梅溪湖店）', type: '门店号', store: '梅溪湖店', people: '梅溪湖周边居民、上班族', focus: '区域生活、工作日午餐、附近用餐', fans: 368 },
  { id: 'campus', name: '饱里宝气轻食校园号', type: '校园号', store: '河西大学城店', people: '大学生、考研党', focus: '校园日常、真实体验、学习场景', fans: 906 }
];
const defaults = { tasks: [{ id: 'morning', time: '上午', channel: '朋友圈', title: '发布今日菜单与门店日常', done: false }, { id: 'noon', time: '中午', channel: '小红书', title: '发布午餐场景内容', done: false }, { id: 'afternoon', time: '下午', channel: '社群', title: '发起一个菜单互动问题', done: false }, { id: 'evening', time: '晚上', channel: '抖音', title: '发布晚餐或下课场景', done: false }], notes: [] };
const escPlatform = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function readPlatform() { try { const saved = JSON.parse(localStorage.getItem(PLATFORM_KEY) || '{}'); return { ...defaults, ...saved, tasks: Array.isArray(saved.tasks) ? saved.tasks : defaults.tasks, notes: Array.isArray(saved.notes) ? saved.notes : [] }; } catch { return { ...defaults, tasks: [...defaults.tasks], notes: [] }; } }
function writePlatform(value) { localStorage.setItem(PLATFORM_KEY, JSON.stringify(value)); }
function readMetrics() { try { return JSON.parse(localStorage.getItem(METRIC_KEY) || '[]').filter(Boolean); } catch { return []; } }
function writeMetrics(value) { localStorage.setItem(METRIC_KEY, JSON.stringify(value)); }
function getAssetsPlatform() { try { return JSON.parse(localStorage.getItem('BLBQ_V15_ASSETS') || '[]'); } catch { return []; } }
function getLearnPlatform() { try { return JSON.parse(localStorage.getItem('BLBQ_V14_LEARNING') || '[]'); } catch { return []; } }
function platformContext() { return `${$p('store')?.value || '当前门店'} · ${$p('people')?.value || '目标人群'} · ${$p('scene')?.value || '今日场景'}`; }
function currentContextObject() { return { store: $p('store')?.value || '当前门店', people: $p('people')?.value || '目标人群', scene: $p('scene')?.value || '今日场景', dishes: $p('dishes')?.value || '', style: $p('style')?.value || '真实', depth: $p('depth')?.value || '标准', mode: $p('mode')?.value || 'auto', account: $p('accountSelect')?.value || '饱里宝气品牌主号', sellingPoints: $p('sellingPoints')?.value || '' }; }
function platformShell(title, subtitle, body, badge = '本地可用') { return `<div class="platform-head"><div><h3>${escPlatform(title)}</h3><p>${escPlatform(subtitle)}</p></div><span class="badge">${escPlatform(badge)}</span></div>${body}`; }
function renderHomeDashboard() {
  const box = $p('homeDashboard'); if (!box) return;
  const assets = getAssetsPlatform(); const learning = getLearnPlatform(); const platform = readPlatform(); const scheduled = assets.filter((item) => item.planDate).length; const openTasks = platform.tasks.filter((item) => !item.done).length;
  box.innerHTML = `<div class="card dashboard-card"><div class="cardhead"><div><h3>品牌运营驾驶舱</h3><p>从账号、门店、内容、营销和数据开始今天的运营。</p></div><span class="badge">${openTasks} 项待办</span></div><div class="metric-grid dashboard-metrics"><div class="metric"><strong>${accounts.length}</strong><span>账号矩阵</span></div><div class="metric"><strong>${assets.length}</strong><span>内容资产</span></div><div class="metric"><strong>${scheduled}</strong><span>已排期</span></div><div class="metric"><strong>${learning.length}</strong><span>学习素材</span></div></div><div class="dashboard-foot"><span>当前上下文：${escPlatform(platformContext())}</span><button class="btn ghost" type="button" data-page="data">查看数据中心</button></div></div>`;
  const modules = $p('osModuleGrid'); if (modules) modules.innerHTML = renderOsCards();
}
function renderOsCards() { return `<div class="os-grid"><button class="os-card" data-page="create"><span class="os-icon">✎</span><b>AI 创作</b><small>小红书、抖音、社群、朋友圈</small><em>一键爆文 →</em></button><button class="os-card" data-page="marketing"><span class="os-icon">⚑</span><b>营销中心</b><small>活动策划、热点、爆文推荐、日历</small><em>安排营销 →</em></button><button class="os-card" data-page="assets"><span class="os-icon">▤</span><b>内容库</b><small>图片、视频、文案、模板和 Prompt</small><em>管理资产 →</em></button><button class="os-card" data-page="data"><span class="os-icon">◒</span><b>数据中心</b><small>账号、内容、门店和营销数据</small><em>查看分析 →</em></button><button class="os-card" data-page="brand"><span class="os-icon">◇</span><b>门店与品牌</b><small>门店数据库、账号矩阵、品牌知识库</small><em>维护资料 →</em></button><button class="os-card" data-page="learn"><span class="os-icon">♧</span><b>学习中心</b><small>沉淀爆款、规则和专业种草素材</small><em>持续学习 →</em></button></div>`; }
function taskBoard() { const data = readPlatform(); return `<div class="task-board"><div class="task-board-head"><b>今日执行清单</b><span class="help">勾选后会保存在当前浏览器</span></div>${data.tasks.map((task) => `<label class="task-row"><input type="checkbox" ${task.done ? 'checked' : ''} onchange="togglePlatformTask('${escPlatform(task.id)}', this.checked)"><span class="task-time">${escPlatform(task.time)}</span><span class="task-channel">${escPlatform(task.channel)}</span><span class="task-title">${escPlatform(task.title)}</span></label>`).join('')}<div class="task-add"><input id="newPlatformTask" placeholder="新增一项运营待办"><button class="btn ghost" onclick="addPlatformTask()">添加</button></div></div>`; }
function renderMarketing() { return platformShell('营销中心', '把热点、活动和日历变成可执行的增长动作。', `${taskBoard()}<div class="platform-grid marketing-grid"><article class="platform-card"><b>AI 活动策划</b><p>围绕开学、考试周、会员日和节日生成完整营销方案。</p><button class="btn primary" onclick="generatePlatformCopy('活动')">生成活动方案</button></article><article class="platform-card"><b>今日热点</b><p>联网分析暂未接入，先用门店、人群和场景生成今日选题。</p><button class="btn soft" onclick="generatePlatformCopy('热点')">生成今日选题</button></article><article class="platform-card"><b>爆文推荐</b><p>根据账号定位给出发布时间、标题方向和关键词建议。</p><button class="btn soft" onclick="generatePlatformCopy('爆文')">生成爆文方向</button></article><article class="platform-card"><b>营销日历</b><p>查看今天发什么、哪个账号发布、任务是否完成。</p><button class="btn ghost" onclick="addPlatformTask()">新增日历任务</button></article></div><div class="marketing-notes"><b>运营备注</b><div id="platformNotes">${renderNotes(readPlatform().notes)}</div></div><div id="platformOutput" class="platform-output">选择一个营销模块开始。</div>`); }
function renderNotes(notes) { if (!notes.length) return '<div class="empty compact-empty">还没有运营备注，可先新增一条合作或复盘待办。</div>'; return notes.slice(0, 8).map((note) => `<div class="note-row"><span>${escPlatform(note.title)}</span><small>${new Date(note.createdAt).toLocaleDateString('zh-CN')}</small></div>`).join(''); }
function metricSummary(metrics) { return metrics.reduce((sum, item) => ({ exposure: sum.exposure + Number(item.exposure || 0), likes: sum.likes + Number(item.likes || 0), favorites: sum.favorites + Number(item.favorites || 0), comments: sum.comments + Number(item.comments || 0), leads: sum.leads + Number(item.leads || 0), orders: sum.orders + Number(item.orders || 0) }), { exposure: 0, likes: 0, favorites: 0, comments: 0, leads: 0, orders: 0 }); }
function metricChart(metrics) { const recent = [...metrics].sort((a, b) => String(a.date).localeCompare(String(b.date))).slice(-7); if (!recent.length) return '<div class="chart-empty">录入数据后，这里会显示趋势。</div>'; const max = Math.max(...recent.map((item) => Number(item.exposure || 0)), 1); return `<div class="metric-chart">${recent.map((item) => { const height = Math.max(8, Math.round(Number(item.exposure || 0) / max * 100)); return `<div class="chart-col"><div class="chart-value">${Number(item.exposure || 0)}</div><div class="chart-bar" style="height:${height}%"></div><span>${escPlatform(String(item.date).slice(5))}</span></div>`; }).join('')}</div>`; }
function renderData() { const assets = getAssetsPlatform(); const learning = getLearnPlatform(); const metrics = readMetrics(); const summary = metricSummary(metrics); return platformShell('数据中心', '分析账号、内容、门店和营销表现，先用本地数据跑通闭环。', `<div class="metric-grid"><div class="metric"><strong>${accounts.length}</strong><span>账号矩阵</span></div><div class="metric"><strong>${assets.length}</strong><span>内容资产</span></div><div class="metric"><strong>${assets.filter((x) => x.status === '已发布').length}</strong><span>已发布内容</span></div><div class="metric"><strong>${metrics.length}</strong><span>经营记录</span></div></div><div class="data-summary"><div><b>${summary.exposure}</b><span>累计曝光</span></div><div><b>${summary.likes}</b><span>点赞</span></div><div><b>${summary.favorites}</b><span>收藏</span></div><div><b>${summary.comments}</b><span>评论</span></div><div><b>${summary.leads}</b><span>私信/线索</span></div><div><b>${summary.orders}</b><span>下单</span></div></div><div class="card-inner"><div class="cardhead"><div><h4>近 7 条曝光趋势</h4><p>录入真实数据，不要为了好看填入虚构指标。</p></div></div>${metricChart(metrics)}</div><div class="card-inner"><div class="cardhead"><div><h4>新增经营记录</h4><p>按门店、日期和渠道记录曝光、互动、线索与下单。</p></div></div><div class="metric-form"><input id="metricDate" type="date"><input id="metricStore" value="${escPlatform(currentContextObject().store)}" placeholder="门店"><input id="metricChannel" value="小红书" placeholder="渠道"><input id="metricExposure" type="number" min="0" placeholder="曝光"><input id="metricLikes" type="number" min="0" placeholder="点赞"><input id="metricFavorites" type="number" min="0" placeholder="收藏"><input id="metricComments" type="number" min="0" placeholder="评论"><input id="metricLeads" type="number" min="0" placeholder="私信/线索"><input id="metricOrders" type="number" min="0" placeholder="下单"><button class="btn primary" onclick="saveMetricRecord()">保存数据</button></div></div><div class="card-inner"><div class="cardhead"><div><h4>账号矩阵</h4><p>当前先维护账号定位和粉丝基线，后续接入数据接口。</p></div></div><div class="account-grid">${accounts.map((account) => `<article class="account-card"><div class="account-card-top"><b>${escPlatform(account.name)}</b><span class="asset-chip">${escPlatform(account.type)}</span></div><p>${escPlatform(account.store)} · ${escPlatform(account.people)}</p><small>${escPlatform(account.focus)} · 粉丝 ${account.fans}</small></article>`).join('')}</div></div><div class="card-inner"><div class="cardhead"><div><h4>最近记录</h4><p>${learning.length} 条学习素材已纳入 AI 上下文。</p></div><button class="btn danger" onclick="clearMetricRecords()">清空记录</button></div><div class="metric-records">${metrics.slice().reverse().slice(0, 8).map((item) => `<div class="metric-record"><span>${escPlatform(item.date)} · ${escPlatform(item.store)} · ${escPlatform(item.channel)}</span><b>曝光 ${Number(item.exposure || 0)} / 下单 ${Number(item.orders || 0)}</b></div>`).join('') || '<div class="empty compact-empty">暂无经营记录。</div>'}</div></div>`); }
function renderBrand() { return platformShell('门店与品牌', '统一维护品牌、门店、菜单、账号和内容规则，AI 生成时自动读取现有知识库。', `<div class="platform-grid"><article class="platform-card"><b>品牌知识库</b><p>品牌定位、口号、核心卖点、内容边界和品牌语气。</p><button class="btn soft" onclick="openKnowledge('brand.md')">查看品牌规则</button></article><article class="platform-card"><b>门店数据库</b><p>林科大、梅溪湖、河西大学城的区域和场景差异。</p><button class="btn soft" onclick="openKnowledge('stores.md')">查看门店规则</button></article><article class="platform-card"><b>菜单数据库</b><p>菜品结构、搭配表达、价格和事实校验边界。</p><button class="btn soft" onclick="openKnowledge('menu.md')">查看菜单规则</button></article><article class="platform-card"><b>账号矩阵</b><p>品牌主号、门店号、健康餐号和校园号的定位与分发。</p><button class="btn soft" onclick="showAccountMatrix()">查看账号矩阵</button></article></div><div id="platformOutput" class="platform-output">知识库文件位于 /knowledge，可直接维护。现有 Prompt 业务逻辑保持不变。</div>`); }
function renderSecretary() { return platformShell('AI 运营秘书', '把“最近订单下降怎么办”转成结合门店、账号、菜品、人群和场景的行动建议。', `<div class="secretary"><label>告诉运营秘书当前问题</label><textarea id="secretaryInput" placeholder="例如：最近林科大订单下降怎么办？"></textarea><div class="actions"><button class="btn primary" onclick="askSecretary()">生成运营建议</button><button class="btn soft" onclick="fillSecretary()">使用示例问题</button></div><div class="help">在线时复用现有 Gemini + Prompt + 知识库链路；在线失败时自动给出本地行动建议。</div></div><div id="platformOutput" class="platform-output">运营建议会结合当前门店、人群、场景和菜品生成。</div>`); }
function renderSystem() { const assets = getAssetsPlatform(); const metrics = readMetrics(); return platformShell('系统设置', '管理运行模式、数据边界和未来扩展接口。', `<div class="platform-grid"><article class="platform-card"><b>当前运行上下文</b><p>${escPlatform(platformContext())}</p><span class="asset-chip">在线 Provider + 本地兜底</span></article><article class="platform-card"><b>AI 模型管理</b><p>默认 Gemini，当前保留本地兜底；OpenAI、Claude、DeepSeek、Qwen 等作为后续 Provider 适配。</p><span class="asset-chip">Adapter 已预留</span></article><article class="platform-card"><b>数据概览</b><p>内容资产 ${assets.length} 条，经营记录 ${metrics.length} 条，账号 ${accounts.length} 个。</p><span class="asset-chip">LocalStorage</span></article><article class="platform-card"><b>数据备份</b><p>导出当前平台数据，换设备时可手动保存备份。</p><button class="btn soft" onclick="exportPlatformData()">导出平台数据</button><button class="btn ghost" onclick="importPlatformData()">导入平台数据</button></article></div><div id="platformOutput" class="platform-output">当前版本不上传本地资产；Gemini 密钥仍由 Netlify Function 读取。</div>`); }
function renderPlatformPage(page) { const box = $p('platformBox'); if (!box) return; const views = { marketing: renderMarketing, data: renderData, brand: renderBrand, secretary: renderSecretary, system: renderSystem }; box.innerHTML = (views[page] || renderMarketing)(); }
window.renderHomeDashboard = renderHomeDashboard; window.renderPlatformPage = renderPlatformPage;
window.generatePlatformCopy = async (type) => { const output = $p('platformOutput'); const context = platformContext(); const copy = { 社群: `【今日社群话术】\n${context}\n\n午餐时间到了，今天想看哪道菜？欢迎在群里告诉我们。\n\n【互动问题】\n你们更想看牛肉、虾仁还是时蔬搭配？`, 活动: `【活动方案】\n主题：${context}饭点互动日\n机制：评论区选菜 + 门店现场小福利\n执行：先发社群互动，再生成小红书、抖音和朋友圈配套内容。\n注意：价格、库存和活动期限发布前由门店确认。`, 校园: `【校园运营建议】\n围绕${context}，今天安排午餐场景、社群选菜互动、晚八下课内容和晚上数据复盘。`, 热点: `【今日选题建议】\n先围绕${context}观察校园、减脂和本地美食话题，再用真实门店内容承接，不直接照搬热点。`, 爆文: `【爆文方向】\n账号：${escPlatform($p('accountSelect')?.value || '当前账号')}\n标题方向：真实场景 + 明确痛点 + 菜品结果\n关键词：${escPlatform(currentContextObject().people)}、${escPlatform(currentContextObject().store)}、下课吃饭、轻食不挨饿` }; if (output) output.textContent = copy[type] || copy.社群; };
window.togglePlatformTask = (id, done) => { const data = readPlatform(); const task = data.tasks.find((item) => item.id === id); if (task) task.done = done; writePlatform(data); renderHomeDashboard(); };
window.addPlatformTask = () => { const input = $p('newPlatformTask'); const title = input?.value.trim() || '新增营销日历任务'; const data = readPlatform(); data.tasks.push({ id: `task-${Date.now().toString(36)}`, time: '待安排', channel: '运营', title, done: false }); writePlatform(data); renderPlatformPage('marketing'); renderHomeDashboard(); window.toast?.('已加入今日执行清单'); };
window.fillSecretary = () => { const input = $p('secretaryInput'); if (input) input.value = `${$p('store')?.value || '当前门店'}最近互动和订单下降，今天应该做什么？`; };
window.askSecretary = async () => { const output = $p('platformOutput'); const question = $p('secretaryInput')?.value.trim() || '今天应该做什么？'; if (output) output.textContent = 'AI 运营秘书正在分析…'; const fallback = `【AI 运营秘书建议】\n问题：${question}\n\n1. 先核对最近 7 天曝光、收藏、私信和下单。\n2. 中午前发布一条${currentContextObject().store}真实菜单与饭点痛点内容。\n3. 下午在社群发起选菜问题，晚上录入数据复盘。\n\n下一步：去 AI 创作生成标题、正文、标签和评论，再保存到内容库排期。`; try { if (!window.BLBQAI?.generate) throw new Error('AI 适配层未加载'); const result = await window.BLBQAI.generate({ task: 'article', context: { ...currentContextObject(), mode: currentContextObject().mode }, extra: `你是饱里宝气的 AI 运营秘书。请回答：${question}。请输出问题判断、优先级、行动清单、内容方向和人工核对数据。`, learning: getLearnPlatform().slice(0, 20) }); if (output) output.textContent = `【AI 运营秘书建议｜${result.source === 'gemini' ? 'Gemini' : '本地兜底'}】\n问题：${question}\n\n${result.text}`; } catch { if (output) output.textContent = `${fallback}\n\n（在线 AI 暂不可用，已使用本地兜底。）`; } };
window.addPlatformNote = (title) => { const data = readPlatform(); data.notes.unshift({ id: Date.now().toString(36), title, createdAt: new Date().toISOString() }); writePlatform(data); renderPlatformPage('marketing'); renderHomeDashboard(); window.toast?.('已加入运营待办'); };
window.saveMetricRecord = () => { const item = { id: Date.now().toString(36), date: $p('metricDate')?.value || new Date().toISOString().slice(0, 10), store: $p('metricStore')?.value.trim() || '当前门店', channel: $p('metricChannel')?.value.trim() || '未填写', exposure: Number($p('metricExposure')?.value || 0), likes: Number($p('metricLikes')?.value || 0), favorites: Number($p('metricFavorites')?.value || 0), comments: Number($p('metricComments')?.value || 0), leads: Number($p('metricLeads')?.value || 0), orders: Number($p('metricOrders')?.value || 0) }; const metrics = readMetrics(); metrics.push(item); writeMetrics(metrics); renderPlatformPage('data'); window.toast?.('经营数据已保存'); };
window.clearMetricRecords = () => { if (!readMetrics().length) return window.toast?.('暂无经营记录'); if (confirm('确定清空本地经营记录吗？')) { localStorage.removeItem(METRIC_KEY); renderPlatformPage('data'); window.toast?.('经营记录已清空'); } };
window.openKnowledge = async (file) => { const output = $p('platformOutput'); if (!output) return; try { const response = await fetch(`knowledge/${file}`); output.textContent = response.ok ? await response.text() : '知识库文件暂不可访问'; } catch { output.textContent = '本地文件读取失败，请检查服务或直接编辑 knowledge 目录。'; } };
window.showAccountMatrix = () => { const output = $p('platformOutput'); if (output) output.innerHTML = `<div class="account-grid">${accounts.map((account) => `<article class="account-card"><b>${escPlatform(account.name)}</b><span class="asset-chip">${escPlatform(account.type)}</span><p>${escPlatform(account.store)} · ${escPlatform(account.people)}</p><small>${escPlatform(account.focus)} · 粉丝 ${account.fans}</small></article>`).join('')}</div>`; };
window.exportPlatformData = () => { const payload = { platform: readPlatform(), metrics: readMetrics(), accounts, exportedAt: new Date().toISOString() }; const text = JSON.stringify(payload, null, 2); if (navigator.clipboard) navigator.clipboard.writeText(text); else window.prompt('复制平台数据', text); window.toast?.('平台数据已复制，可保存为 JSON'); };
window.importPlatformData = () => { const raw = window.prompt('粘贴平台数据 JSON'); if (!raw) return; try { const data = JSON.parse(raw); if (data.platform) writePlatform(data.platform); if (Array.isArray(data.metrics)) writeMetrics(data.metrics); renderPlatformPage('system'); renderHomeDashboard(); window.toast?.('平台数据导入成功'); } catch { window.alert('JSON 格式不正确'); } };
document.addEventListener('DOMContentLoaded', renderHomeDashboard);
